const { EntitySchema } = require("typeorm");
const { decimalTransformer } = require("./helpers");

module.exports = new EntitySchema({
  name: "Quotation",
  tableName: "quotations",
  columns: {
    id: { type: "text", primary: true },
    quotationNumber: { name: "quotation_number", type: "text", unique: true },
    quotationDate: { name: "quotation_date", type: "date" },
    projectName: { name: "project_name", type: "text" },
    projectLocation: { name: "project_location", type: "text" },
    clientName: { name: "client_name", type: "text" },
    clientCompany: { name: "client_company", type: "text" },
    customerId: { name: "customer_id", type: "text", nullable: true },
    subtotal: {
      type: "decimal",
      precision: 14,
      scale: 2,
      default: 0,
      transformer: decimalTransformer,
    },
    freight: {
      type: "decimal",
      precision: 14,
      scale: 2,
      default: 0,
      transformer: decimalTransformer,
    },
    installationCharge: {
      name: "installation_charge",
      type: "decimal",
      precision: 14,
      scale: 2,
      default: 0,
      transformer: decimalTransformer,
    },
    gstPercentage: {
      name: "gst_percentage",
      type: "decimal",
      precision: 5,
      scale: 2,
      default: 18,
      transformer: decimalTransformer,
    },
    gstAsExtra: { name: "gst_as_extra", type: "boolean", default: true },
    gstAmount: {
      name: "gst_amount",
      type: "decimal",
      precision: 14,
      scale: 2,
      default: 0,
      transformer: decimalTransformer,
    },
    grandTotal: {
      name: "grand_total",
      type: "decimal",
      precision: 14,
      scale: 2,
      default: 0,
      transformer: decimalTransformer,
    },
    amountInWords: { name: "amount_in_words", type: "text", default: "" },
    status: { type: "text", default: "draft" },
    companySnapshot: { name: "company_snapshot", type: "jsonb" },
    pdfPath: { name: "pdf_path", type: "text", nullable: true },
    createdById: { name: "created_by_id", type: "text", nullable: true },
    createdAt: { name: "created_at", type: "timestamp", createDate: true },
    updatedAt: { name: "updated_at", type: "timestamp", updateDate: true },
  },
  indices: [
    { name: "quotations_status_idx", columns: ["status"] },
    { name: "quotations_quotation_date_idx", columns: ["quotationDate"] },
    { name: "quotations_client_company_idx", columns: ["clientCompany"] },
  ],
  relations: {
    customer: {
      type: "many-to-one",
      target: "Customer",
      joinColumn: { name: "customer_id" },
      nullable: true,
      onDelete: "SET NULL",
      inverseSide: "quotations",
    },
    createdBy: {
      type: "many-to-one",
      target: "User",
      joinColumn: { name: "created_by_id" },
      nullable: true,
      onDelete: "SET NULL",
      inverseSide: "quotations",
    },
    items: {
      type: "one-to-many",
      target: "QuotationItem",
      inverseSide: "quotation",
      cascade: true,
    },
    terms: {
      type: "one-to-one",
      target: "QuotationTerms",
      inverseSide: "quotation",
      cascade: true,
    },
  },
});
